on:
  push: {}
  pull_request: { }
  release:
    types:
      - created

name: Build CI

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.cross }}
    strategy:
      matrix:
        cross:
          - linux-x64
          - linux-arm64
          - windows-shared-x86
          - windows-shared-x64
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16'
      - name: Chmod scripts
        run: |
          chmod +x gradlew
          chmod +x .scripts/build.sh
          chmod +x .scripts/setup_docker.sh
      - name: Build java
        run: ./gradlew build
      - name: Build native (${{ matrix.cross }})
        run: .scripts/setup_docker.sh
        env:
          CROSS: ${{ matrix.cross }}
      - name: Archive NativeLib artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.cross }}
          path: |
            native/cmake-build-release/bin
  build-macos:
    runs-on: macos-latest
    name: Build on MacOS
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16'
      - name: Chmod scripts
        run: |
          chmod +x gradlew
          chmod +x .scripts/build.sh
          chmod +x .scripts/setup_docker.sh
      - name: Build java
        run: ./gradlew build
      - name: Build native
        run: .scripts/build.sh
        env:
          CROSS: MacOS
      - name: Archive NativeLib artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos
          path: |
            native/cmake-build-release/bin

  build-jars:
    runs-on: ubuntu-latest
    name: Upload jars
    needs:
      - build-macos
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '16'
      - name: pre setup
        run: |
          chmod +x gradlew
          mkdir tmp
          mkdir tmp/artifacts
      - uses: actions/download-artifact@v2
        with:
          path: tmp/artifacts
      - name: Chmod scripts
        run: |
          chmod +x gradlew
      - name: Clean caches
        run: ./gradlew clean
      - name: Build jars
        run: |
          ./gradlew packNative
          ./gradlew clean
          ./gradlew build
          find .
      - name: Archive Jar artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jars
          path: |
            build/libs
      - name: Upload release assets
        if: "${{ github.event_name == 'release' }}"
        run: ./gradlew :ci-helper:uploadReleaseAssets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POST_URL: ${{ github.event.release.upload_url }}
